version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data:/data
